export interface Doctor {
    id: number,
    name: string,
    gender: string,
    qualification: string,
    email: string,
    fees: number,
    experienceStart: string,
    specialization: string,
    leaveStart: string,
    leaveEnd: string,
    rating: number,
    status: string,
    userName: string,
    password: string,
    profileImgUrl: string,
}
